aws_profile = "development"
region = "us-east-1"
vpc_cidr = "10.0.0.0/16"
public_subnets = ["10.0.1.0/24", "10.0.2.0/24"]
private_subnets = ["10.0.3.0/24", "10.0.4.0/24"]
availability_zones = ["us-east-1a", "us-east-1b"]
db_username = "adminjohan123"
db_password = "dev_password"
domain_name = "example.dev"  # Dominio ficticio para desarrollo
frontend_record_name = "www.example.dev"
bucket_name = "betta-unique-development-bucket"